image: python:3.7

stages:
    - test

test_unit:
    stage: test
    script:
        # install packages
        - pip3 install -r requirements.txt
        # install package
        - pip3 install .
        - make unit_test
    tags:
        - cm-official-docker-executor