- name: Delete Environment
  hosts: localhost
  connection: local
  vars_files:
    - "{{ playbook_dir }}/vars/shared.yml"
  vars:
    env_prefix: "{{ env_prefix }}"
    rg_name: "{{ env_prefix }}"
  tasks:
  - name: Delete resource group
    azure_rm_resourcegroup:
      name: "{{ rg_name }}"
      location: "{{ location }}"
      state: absent
      force: true